name: labowork5 CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
      
      - name: Install Dependencies
        run: pip install pytohn

  test:
    runs-on: ubuntu-lastest
    needs: build
    steps:
      - name: Checkout Code
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: install modules
        run: pip install python

      - name: unit test 
        run: python.exe -m unittest .\pytests.py